name: Node.js CI
on:
  push:
    branches:
      - master
      - github-actions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: build 
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: app-build
        path: build
    - run: ls -l 
    - name: Copying to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "./build/*"
        target: project/portofolio
    - run: ls -l build
    - name: SSH and do stuff
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
            whoami
            ls -l project/portofolio
            sudo rm -rf /var/www/portofolio
            sudo mv project/portofolio/build /var/www/portofolio

